### ISSUE TITLE
Unable to import stickers

### ISSUE THREAD

**Issue by whew-inc** [apsun/uSticker#18]
LineageOS 16 with MicroG/Playstore.

--- 

App version: 1.5.2 (13) 
Gboard version: 8.9.14.285858165-release-arm64-v8a (26891414) 
Android version: 9 (API28) 
Exception stacktrace: 
```
com.google.firebase.FirebaseApiNotAvailableException: API: AppIndexing.API is not available on this device.
	at com.google.firebase.FirebaseExceptionMapper.getException(Unknown Source:3)
	at com.google.android.gms.common.api.internal.zag.zaa(Unknown Source:9)
	at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zac(Unknown Source:9)
	at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.onConnectionFailed(Unknown Source:32)
	at com.google.android.gms.common.api.internal.zabo.run(Unknown Source:23)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.google.android.gms.internal.base.zap.dispatchMessage(Unknown Source:1)
	at android.os.Looper.loop(Looper.java:193)
	at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by apsun** [comment]
Hmm unfortunately the only way (afaik) to get stickers into Gboard is via Firebase, which I suppose has a dependency on Google Play services. Not sure if anything can be done in this case :-(

**Comment by whew-inc** [comment]
Aww, that sucks. I really miss my stickers, so I think I'm going back to stock for now then.
Great app btw!
