### ISSUE TITLE
Error when folder has .nomedia

### ISSUE THREAD

**Issue by pbanj** [apsun/uSticker#41]
I put a .nomedia file in the stirkers folder so they stop showing in every app I open but this causes the app to error and then the stickers can't be sent even if they are still showing in gboard. If you have the time it'd be nice to be able to have a .nomedia file in the folder without it causing any issues.

**Comment by apsun** [comment]
What is the error?

**Comment by pbanj** [comment]
well it was some java error. but when i just tried to get it to do it again it just said it found 0 files. i knew i should have taken a screen shot. i clicked the report button but i assume it did nothing

**Comment by apsun** [comment]
The report button copies the error to your clipboard. It used to create the issue automatically if you were logged in but it ended up causing users to spam the issue tracker, so I turned that off. Unfortunately I can't reproduce this on my end so without the actual error I can't fix this, sorry.

**Comment by pbanj** [comment]
oh i understand. if it happens again ill make sure to save the error

**Comment by pbanj** [comment]
uSticker version: 1.5.4 (15) 
Gboard version: 9.8.04.328163918-beta-arm64-v8a (38012162) 
Android version: 11 (API30) 
Exception stacktrace: 
```
java.lang.IllegalStateException: java.io.FileNotFoundException: No item at content://media/external/downloads/151275
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2381)
	at android.os.Parcel.createException(Parcel.java:2357)
	at android.os.Parcel.readException(Parcel.java:2340)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:472)
	at android.content.ContentResolver.query(ContentResolver.java:1183)
	at android.content.ContentResolver.query(ContentResolver.java:1115)
	at android.content.ContentResolver.query(ContentResolver.java:1071)
	at com.crossbowffs.usticker.StickerScanner.traverseDirectory(StickerScanner.kt:4)
	at com.crossbowffs.usticker.StickerScanner.run(StickerScanner.kt:4)
	at com.crossbowffs.usticker.FailableAsyncTask.doInBackground(FailableAsyncTask.kt:1)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
```

**Comment by pbanj** [comment]
Not sure if the same error, but just got this

**Comment by apsun** [comment]
Is your sticker directory on external storage that has been removed? (Try selecting the directory again)

**Comment by pbanj** [comment]
> 
> 
> Is your sticker directory on external storage that has been removed? (Try selecting the directory again)

ya selecting it again fixed it. seem 11 reset storage perms as ive started to see it in more apps

**Comment by apsun** [comment]
:-(

That's useful info, I'll add a handler for `FileNotFoundException` and make it force you to reselect the folder.
