### ISSUE TITLE
Refresh sticker index fails in Android Q

### ISSUE THREAD

**Issue by ghost** [apsun/uSticker#8]
Get "Refresh failed" when trying to refresh Sticker index in Android Q.

- App version: uSticker 1.4.2
- Build: QPP1.190205.018.b4 (Android Q Developer Preview 1)
- Phone: Pixel 2 (non-XL)

`
com.google.firebase.FirebaseException: TransactionTooLargeException: data parcel size 1223192 bytes
	at com.google.firebase.FirebaseExceptionMapper.getException(Unknown Source:3)
	at com.google.android.gms.common.api.internal.zag.zaa(Unknown Source:15)
	at com.google.android.gms.common.api.internal.zag.zaa(Unknown Source:10)
	at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zac(Unknown Source:167)
	at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zab(Unknown Source:139)
	at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zaa(Unknown Source:105)
	at com.google.android.gms.common.api.internal.GoogleApiManager.handleMessage(Unknown Source:145)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:209)
	at android.os.HandlerThread.run(HandlerThread.java:67)
`

![Screenshot (Mar  20, 2019 11_25_25](https://user-images.githubusercontent.com/17794167/54736361-efe52f80-4b67-11e9-99a3-9b9496e144ce.png)

**Comment by apsun** [comment]
Thanks, how many stickers do you have? I want to see if this can be fixed by reducing the number of stickers we send at once to Firebase.

**Comment by ghost** [comment]
Oh there we go. I had about 8.44MB of Stickers because of one fairly large one I didn't notice after I restored my phone for DP1. Once I dropped the folder size to below ~7.5MB it allowed me to refresh.

**Comment by apsun** [comment]
Okay, cool! So it's not an Android Q related issue, then. The size limit is based on the number of files you have along with how long their filenames are. The actual image size doesn't matter here. Currently the app sends a fixed 1000 files at a time to Firebase, but clearly that's still too high. Can you post how many files you have? That should give me a rough estimate of where I should set the limit at.

**Comment by ghost** [comment]
So when I started it was 17 folders with 682 files. 
I removed a folder at a time refreshing in between and it allowed me to refresh the index with 14 folders and 562 files. Each folder contains about 40 files, so I guess it maxes out somewhere between 562 and 600 files.

**Comment by apsun** [comment]
Wow, you sure have a lot of stickers ;-p

I think setting the limit around 250 should be fairly safe and leave plenty of buffer room for people with super long filenames. I'll fix this later tonight.

**Comment by ghost** [comment]
Cheers thanks for your help. And yeah I should probably clear out some of those folders...

**Comment by apsun** [comment]
Hopefully fixed in 1.4.3. Just uploaded it to the Play Store.
